### ISSUE TITLE
Compilation Issues with Intel Compiler

### ISSUE THREAD

**Issue by wbinventor** [mit-crpg/OpenMOC#300] opened 2016-04-06 15:09 UTC
I recently tried building the code with the Intel compiler and discovered that the code no longer builds due to the following error:

``` bash
src/ParallelHashMap.h(790): error: invalid entity for this variable list in omp clause
  #pragma omp flush(_announce)
```

Although no one that I know of is routinely using the Intel over GCC for OpenMOC, it would be nice to fix this issue since we do claim that the code can be built with GCC, Intel and Clang (though only GCC is included in CI for simplicity).

**Comment by GiudGiud** [comment] 2019-07-02 19:38
This has been fixed on 3D MOC, soon to replace develop
flushing a pointer was not what was intended by #pragma omp flush(_announce), we wanted to flush the array of pointers.
GCC was not complaining about it.

**Closed by GiudGiud** 2019-07-02 19:38 UTC
Labels: Bug, Configuration Management
